### PR TITLE
Changed Vault-dependency in pom.xml

### PR DESCRIPTION
**Pull request by Androkai**
If you're having no special reason to deliver Vault as a file with the AreaShop-repo feel free to change to this way :)

### CODE REVIEW

**Comment by NLthijs48** [comment]
I could not find a Maven repository for Vault, so therefore I had added it this way. Merging it because this is obviously a better way.

**Comment by NLthijs48** [comment]
I cannot get Intellij IDEA to download the dependency, it indicates it cannot find the dependency. Did you test this successfully?

**Comment by Androkai** [comment]
Tested it building direct with Maven which works. See your Jenkins.

**Comment by NLthijs48** [comment]
Turns out I'm stupid, had set Maven to offline mode because a while back some repositories were offline which would slow down the build to 10 minutes or so instead of 5 seconds. So that is why it could not get the Vault dependency, it was only looking in my local repository. Works perfectly now that I corrected that.

**Pull request merged**
