### PR TITLE
Update VaultAPI-repo

### PR DESCRIPTION
**Pull request by Androkai**

### CODE REVIEW

**Comment by NLthijs48** [comment]
Cool, I was already looking for a replacement, actually I was about to include the Vault jar in the AreaShop repository again because I could not find a Maven repo for it.

**Comment by Androkai** [comment]
They needed some days but now it's working again: https://github.com/MilkBowl/VaultAPI
And jey, we're back again! [BuildStatus](https://jenkins.androkai.net/job/AreaShop/)

**Comment by NLthijs48** [comment]
I had checked the [Vault page on BukkitDev](https://dev.bukkit.org/bukkit-plugins/vault/) a couple of times, but even now it still shows the old repository.

Cool status button :) The [commit history](https://github.com/NLthijs48/AreaShop/commits/master) of AreaShop also shows the build status since a while.

**Comment by Androkai** [comment]
Nice Jenkins-setup and integration back to GitHub :+1:

**Pull request merged**
