### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by EvilOlaf**

### CODE REVIEW

**Comment by NLthijs48** [comment]
I would prefer that you join the German team of the AreaShop team at [Transifex](https://www.transifex.com/evolution-coding/areashop/) (translation platform), that way you can correct these small mistakes immediately, and also help translating new messages whenever I add some.

Some more information about translating through the Transifex platform can be found on [this page](https://github.com/NLthijs48/AreaShop/wiki/Language-support#translating-on-transifex).

Since I'm automatically pulling the latest translated files from Transifex before I release a new AreaShop version, it does not help much to merge this pull request (since changes would be overwritten), instead I suggest you change these things on Transifex directly (after you joined the German team) or that I make the changes on Transifex (if you are not interested in joining Transifex).

Let me know what you think.

**Comment by EvilOlaf** [comment]
I'll give it a try. Need to explore how this works.

**Comment by NLthijs48** [comment]
Okey cool, let me know if you have any questions about it.

I'll close the 2 pull requests now, since you should be able to easily edit these yourself now.

**Comment by EvilOlaf** [comment]
Honestly this Transifex thing is confusing to me. First of all it is kind a hard to find a special phrase as it tells me often that no matches were found. Also I can dann suggestions and have some suggestions on the other side that look like the have nothing to do with the current phrase...

I don't think I'll contribute much this way, sorry. Like Github more. One change. Purpose file changes. Changes merged, done.

**Comment by NLthijs48** [comment]
It might not be able to find the phrases because the locale strings use variables, for example `You have rented shop-1 until 30 August 2015` has the language string `You rented %0% until %1%.`. The suggestions indeed do not make much sense (they have a percentage next to them indicating how good they are). Those suggestions are only useful if I for example changed the source sentence by 1 or 2 characters, then you can easily select your previous translation again.

The problem with GitHub is that merging won't do anything for me, since the changes will get overwritten when I redownload the translations. So then I would need to make the changes myself in Transifex, which does not seem like a good workflow to me.

I get that the translating part of Transifex might be quite overwhelming at first (especially if you only want to correct 1 word), but for translating things it is very powerful.

**Pull request closed without merging**
