### PR TITLE
Enhacements

### PR DESCRIPTION
**Pull request by goreacraft**
- added requirements ( restrict renting shops unless they have others)
- added custom permissions requirements for shops
- wg 6 colors

### CODE REVIEW

**Comment by goreacraft** [comment]
i think i am breaking the files formatting, if so please deny this poll
i don't do well with github, i am in the learning process so please excuse me

**Comment by goreacraft** [comment]
if u want to contact me i am usually in teamspeak on ip: goreacraft.com

**Comment by NLthijs48** [comment]
I quickly took a look at your pull request (dont have much time currently and it is getting late here), there are indeed some problems with it. I will try to check it completely tomorrow and then I will try to indicate the problems precisely. I indeed saw that you have a TeamSpeak server, I'll join that if i checked your pull request.

Some questions you can maybe already try to answer: What are you trying to achieve with this code? What does it provide for the players and/or admins? Basically try to describe your idea precisely.

**Comment by goreacraft** [comment]
i can show u what i achieved with it if u are willing to join my ftb infinity server
it allows u to have modular dynamic shops:
the modules appear on purchase and when the rent expires it reverts back to initial state so my modification prevents players to get a certain modules unless they have a required one, and so preventing weird things happening

i will be more then happy to show u when u have time

**Comment by NLthijs48** [comment]
**For reference:**
After a conversation on TeamSpeak and joining the server GoreaCraft the goal became clear. The goal was to require a certain region before another region can be bought. He used this system to sell modular shops where you can first buy the basic house and after that buy upgrades for it. These upgrades place a schematic just beside the house so that the shop is expanded with another section.

Because the Pull Request is not in a great shape (details can be found in [this document](https://docs.google.com/document/d/1Bhxal0G0TNZYJFYGSH-0FpxF23j8lHaDEfKAvywex4M/edit?usp=sharing)) we agreed to close this pull request. He gave me the permission to use his work to add it to AreaShop myself (which will probably happen).

**Pull request closed without merging**
